# Generated by Django 6.0.5 on 2026-05-11 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('property_id', models.UUIDField(verbose_name='ID do Imóvel')),
                ('landlord_id', models.UUIDField(verbose_name='ID do Senhorio')),
                ('tenant_id', models.UUIDField(verbose_name='ID do Inquilino')),
                ('contract_type', models.CharField(choices=[('residential', 'Residencial'), ('commercial', 'Comercial'), ('short_term', 'Curto Prazo')], max_length=20, verbose_name='Tipo de Contrato')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('expired', 'Expirado'), ('terminated', 'Terminado')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ativado em')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Expirado em')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Renda Mensal')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Caução')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Duração (meses)')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Método de Pagamento')),
                ('payment_day', models.PositiveIntegerField(default=1, verbose_name='Dia de Pagamento')),
            ],
            options={
                'verbose_name': 'Contrato de Arrendamento',
                'verbose_name_plural': 'Contratos de Arrendamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_end_date', models.DateField(verbose_name='Nova Data de Término')),
                ('new_monthly_rent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nova Renda Mensal')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('landlord_approved', models.BooleanField(default=False, verbose_name='Aprovado pelo Senhorio')),
                ('tenant_approved', models.BooleanField(default=False, verbose_name='Aprovado pelo Inquilino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('landlord_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado pelo Senhorio em')),
                ('tenant_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado pelo Inquilino em')),
                ('landlord_reason', models.TextField(blank=True, null=True, verbose_name='Motivo do Senhorio')),
                ('tenant_reason', models.TextField(blank=True, null=True, verbose_name='Motivo do Inquilino')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.rentalcontract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Renovação de Contrato',
                'verbose_name_plural': 'Renovações de Contrato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.DateField(verbose_name='Mês de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Em Atraso'), ('partial', 'Parcial')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Multa')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência da Transação')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Comprovante')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.rentalcontract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pagamento de Contrato',
                'verbose_name_plural': 'Pagamentos de Contrato',
                'ordering': ['-payment_month'],
                'unique_together': {('contract', 'payment_month')},
            },
        ),
    ]
