# Generated by Django 6.0.5 on 2026-05-11 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição Detalhada')),
                ('property_type', models.CharField(choices=[('luxury_house', 'Casa de Luxo'), ('land', 'Terreno'), ('villa', 'Vivenda'), ('apartment', 'Apartamento'), ('small_house', 'Casa Pequena'), ('room', 'Quarto em Bairro')], max_length=20, verbose_name='Tipo de Imóvel')),
                ('transaction_type', models.CharField(choices=[('sale', 'Venda'), ('rent', 'Arrendamento'), ('short_term_rent', 'Arrendamento Curto Duração')], max_length=20, verbose_name='Tipo de Transação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('price_negotiable', models.BooleanField(default=False, verbose_name='Preço Negociável')),
                ('province', models.CharField(max_length=100, verbose_name='Província')),
                ('municipality', models.CharField(max_length=100, verbose_name='Município')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua')),
                ('reference_point', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ponto de Referência')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Quartos')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Banheiros')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='Vagas de Estacionamento')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área (m²)')),
                ('total_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área Total (m²)')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Mobiliado')),
                ('furniture_description', models.TextField(blank=True, null=True, verbose_name='Descrição dos Móveis')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Disponível a partir de')),
                ('available_until', models.DateField(blank=True, null=True, verbose_name='Disponível até')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('sold', 'Vendido'), ('rented', 'Arrendado'), ('expired', 'Expirado'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('contact_count', models.PositiveIntegerField(default=0, verbose_name='Contatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('deed', 'Escritura'), ('registration', 'Registo'), ('license', 'Licença'), ('tax', 'Documento Fiscal'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Documento')),
                ('document', models.FileField(upload_to='property_documents/', verbose_name='Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='listings.property', verbose_name='Imóvel')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Documento do Imóvel',
                'verbose_name_plural': 'Documentos dos Imóveis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='Imagem')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Imagem do Imóvel',
                'verbose_name_plural': 'Imagens dos Imóveis',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='property_videos/', verbose_name='Vídeo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Thumbnail')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Vídeo do Imóvel',
                'verbose_name_plural': 'Vídeos dos Imóveis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Visualizado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='listings.property', verbose_name='Imóvel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_views', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visualização de Imóvel',
                'verbose_name_plural': 'Visualizações de Imóveis',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'created_at'], name='listings_pr_status_de99a6_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'transaction_type'], name='listings_pr_propert_a8f889_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['province', 'municipality'], name='listings_pr_provinc_22ec4a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='listings_pr_price_ee6360_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['featured'], name='listings_pr_feature_d91b4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyimage',
            unique_together={('property', 'order')},
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['property', 'viewed_at'], name='listings_pr_propert_c2b9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['user', 'viewed_at'], name='listings_pr_user_id_233957_idx'),
        ),
    ]
