# Generated by Django 6.0.6 on 2026-07-24 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_messages', to='listings.property', verbose_name='Imóvel')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem de Imóvel',
                'verbose_name_plural': 'Mensagens de Imóveis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'created_at'], name='listings_pr_propert_643035_idx'), models.Index(fields=['sender', 'receiver', 'created_at'], name='listings_pr_sender__aa65b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(verbose_name='Data Preferida')),
                ('preferred_time', models.TimeField(verbose_name='Horário Preferido')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Realizada')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='listings.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Solicitação de Visita',
                'verbose_name_plural': 'Solicitações de Visita',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'status', 'created_at'], name='listings_pr_propert_c769b7_idx'), models.Index(fields=['buyer', 'created_at'], name='listings_pr_buyer_i_591496_idx')],
            },
        ),
    ]
