# Generated by Django 6.0.5 on 2026-05-11 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_id', models.UUIDField(verbose_name='ID do Imóvel')),
                ('sponsor_id', models.UUIDField(verbose_name='ID do Patrocinador')),
                ('sponsorship_type', models.CharField(choices=[('basic', 'Básico'), ('premium', 'Premium'), ('ultimate', 'Ultimate'), ('featured', 'Destaque')], max_length=20, verbose_name='Tipo de Patrocínio')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('suspended', 'Suspenso')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ativado em')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Expirado em')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Patrocínio',
                'verbose_name_plural': 'Patrocínios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('package_type', models.CharField(choices=[('basic', 'Básico'), ('premium', 'Premium'), ('ultimate', 'Ultimate'), ('featured', 'Destaque')], max_length=20, unique=True, verbose_name='Tipo de Pacote')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duração (dias)')),
                ('priority_level', models.PositiveIntegerField(default=1, verbose_name='Nível de Prioridade')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('features', models.TextField(verbose_name='Características')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pacote de Patrocínio',
                'verbose_name_plural': 'Pacotes de Patrocínio',
                'ordering': ['priority_level', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transferência Bancária'), ('mobile_money', 'Dinheiro Móvel'), ('credit_card', 'Cartão de Crédito'), ('cash', 'Dinheiro')], max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Transação')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Referência')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Comprovante')),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ads.sponsorship', verbose_name='Patrocínio')),
            ],
            options={
                'verbose_name': 'Pagamento de Patrocínio',
                'verbose_name_plural': 'Pagamentos de Patrocínio',
                'ordering': ['-created_at'],
            },
        ),
    ]
