# Generated by Django 6.0.6 on 2026-07-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='sponsor_id',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='listings.property', verbose_name='Imóvel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL, verbose_name='Patrocinador'),
            preserve_default=False,
        ),
    ]
