# Generated by Django 6.0.5 on 2026-05-11 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('closed', 'Fechado'), ('archived', 'Arquivado')], default='active', max_length=20, verbose_name='Status')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_chats', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='listings.property', verbose_name='Imóvel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_chats', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueador')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks', to='listings.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Bloqueio de Chat',
                'verbose_name_plural': 'Bloqueios de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('file', 'Arquivo'), ('location', 'Localização'), ('contact', 'Contato')], default='text', max_length=20, verbose_name='Tipo de Mensagem')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Arquivo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chat', verbose_name='Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.message', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Notificação de Chat',
                'verbose_name_plural': 'Notificações de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['seller', 'status'], name='chat_chat_seller__40fa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['buyer', 'status'], name='chat_chat_buyer_i_13d24b_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['property', 'status'], name='chat_chat_propert_e4def3_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['last_message_at'], name='chat_chat_last_me_94fba2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('property', 'buyer')},
        ),
        migrations.AddIndex(
            model_name='chatblock',
            index=models.Index(fields=['blocker', 'created_at'], name='chat_chatbl_blocker_32d6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='chatblock',
            index=models.Index(fields=['blocked', 'created_at'], name='chat_chatbl_blocked_4bea43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatblock',
            unique_together={('blocker', 'blocked', 'property')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='chat_messag_chat_id_0c7b25_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_872c73_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='chat_chatno_user_id_f660fc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['chat', 'created_at'], name='chat_chatno_chat_id_db1c6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatnotification',
            unique_together={('user', 'message')},
        ),
    ]
